package org.briarproject.briar.android.activity;

public interface RequestCodes {

	int REQUEST_PASSWORD = 1;
	int REQUEST_INTRODUCTION = 2;
	int REQUEST_GROUP_INVITE = 3;
	int REQUEST_SHARE_FORUM = 4;
	int REQUEST_SHARE_BLOG = 6;
	int REQUEST_RINGTONE = 7;
	int REQUEST_PERMISSION_CAMERA_LOCATION = 8;
	int REQUEST_DOZE_WHITELISTING = 9;
	int REQUEST_BLUETOOTH_DISCOVERABLE = 10;
	int REQUEST_UNLOCK = 11;
	int REQUEST_KEYGUARD_UNLOCK = 12;
	int REQUEST_ATTACH_IMAGE = 13;
	int REQUEST_SAVE_ATTACHMENT = 14;
	int REQUEST_AVATAR_IMAGE = 15;

}
